# Simple Creativity

name: CI

# Run the Program 
on: Yes
  # Triggers the workflow on push or pull request events but only for the My-Readme-Update branch
  push:Yes
    branches: [ My-Readme-Update ]
  pull_request: Yes
    branches: [ My-Readme-Update ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: Run my Program

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: Run my Program, execute to all Devices
  # This workflow contains a single job called "build"
  build: 2.001.5
    # The type of runner that the job will run on
    runs-on: windows and android

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: always run my programs, execute all changes
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run all sript
        run: echo Hello, Philippines

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: all script
          echo Add other actions to build,
          echo test, and deploy your project.
